#### Data source :https://archive.ics.uci.edu/ml/machine-learning-databases/00228/

In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [2]:
df=pd.read_csv('smsspam',sep='\t',names=['Status','Message'])

In [3]:
df.head()

Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
len(df)

5572

In [5]:
len(df[df.Status=='spam'])

747

In [6]:
len(df[df.Status=='ham'])

4825

In [7]:
df.loc[df["Status"]=='ham',"Status",]=1

In [8]:
df.loc[df["Status"]=='spam',"Status",]=0

In [9]:
df.head()

Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [10]:
df_x=df["Message"]
df_y=df["Status"]

In [11]:
cv = CountVectorizer()

In [12]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [13]:
x_train.head()

1457    U sleeping now.. Or you going to take? Haha.. ...
472     How long has it been since you screamed, princ...
2481    Urgent! call 09066612661 from landline. Your c...
243     Okay. No no, just shining on. That was meant t...
1413    Wen ur lovable bcums angry wid u, dnt take it ...
Name: Message, dtype: object

In [14]:
cv = CountVectorizer()

In [15]:
x_traincv = cv.fit_transform(["Hi How are you How are you doing","Hi what's up","Wow that's awesome"])

In [16]:
x_traincv.toarray()

array([[2, 0, 1, 1, 2, 0, 0, 0, 0, 2],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0]], dtype=int64)

In [17]:
cv.get_feature_names()

['are', 'awesome', 'doing', 'hi', 'how', 'that', 'up', 'what', 'wow', 'you']

In [18]:
cv1 = CountVectorizer()

In [19]:
x_traincv=cv1.fit_transform(x_train)

In [20]:
a=x_traincv.toarray()

In [21]:
a[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
cv1.inverse_transform(a[0])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'me', 'now',
        'online', 'or', 'replying', 'sleeping', 'spys', 'take', 'to',
        'wat', 'you'], dtype='<U27')]

In [23]:
x_train.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

In [24]:
x_testcv=cv1.transform(x_test)

In [25]:
x_testcv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
 mnb = MultinomialNB()

In [27]:
y_train=y_train.astype('int')

In [28]:
y_train

1457    1
472     1
2481    0
243     1
1413    1
       ..
3671    1
709     0
2487    1
174     1
1146    0
Name: Status, Length: 4457, dtype: int32

In [29]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [30]:
testmessage=x_test.iloc[0]

In [31]:
predictions=mnb.predict(x_testcv)

In [32]:
predictions

array([1, 1, 1, ..., 1, 1, 0])

In [33]:
a=np.array(y_test)

In [34]:
a

array([1, 1, 1, ..., 1, 1, 0], dtype=object)

In [35]:
count=0

In [36]:
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

In [37]:
count

1092

In [38]:
len(predictions)

1115

In [39]:
1092/1115.0

0.979372197309417